pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "TAG: ${TAG}"
                sh "git checkout tags/${TAG}"
            }
        }
        stage('Build'){
            steps{
                dir('/var/jenkins_home/workspace/LAB07/MM400503/Docker'){
                    sh 'docker-compose -f ./docker-compose.yml build --no-cache build-agent'
                }
            }
            post{
                success{
                    echo "Built successfully!"
                }
                failure{
                    echo "Build failed!"
                }
            }
        }// read -r RESULTS <<< "$TEST_OUTPUT"
        stage('Test'){
            steps{
                dir('/var/jenkins_home/workspace/LAB07/MM400503/Docker'){
                    sh 'docker-compose -f ./docker-compose.yml build --no-cache test-agent'
                    sh 'docker-compose  up --force-recreate -d test-agent'
                    sh '''
                        TEST_OUTPUT=`docker-compose logs`
                        TEST_OUTPUT=`echo $TEST_OUTPUT | tr '|' '\n' | grep 'Tests: ' | sed -e 's/^[[:space:]]*//'`
                        PASSED=$(echo $TEST_OUTPUT | awk -F ' ' '{print $3}')
                        TOTAL=$(echo $TEST_OUTPUT | awk -F ' ' '{print $5}')
                        if [ $PASSED == '123' ]; then echo 100% passed; else echo Failure. Rate  $(awk -v var1=$PASSED -v var2=$TOTAL 'BEGIN { print  ( var1 / var2 * 100 ) }'); return 1;fi
                    '''
                }
            }
             post{
                success{
                    echo "Test successfully!"
                }
                failure{
                    echo "Test failed!"
                }
            }
        }
    }

}
