pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "TAG: ${TAG}"
                sh "git checkout tags/${TAG}"
            }
        }
        stage('Build'){
            steps{
                dir('/var/jenkins_home/workspace/LAB07/MM400503/Docker'){
                    sh 'docker-compose build --no-cache '
                    sh 'docker images'
                }
            }
            post{
                success{
                    echo "Built successfully!"
                }
                failure{
                    echo "Build failed!"
                }
            }
        }
    }

}
