services:
  build-agent:
    build:
      context: ../../app
      dockerfile: ../MM400503/Docker/Dockerfile.build
    image: build-agent
  test-agent:
    build: 
      context: ../../app
      dockerfile: ../MM400503/Docker/Dockerfile.test
    depends_on:
      - build-agent
