FROM node:16-alpine as git-install
RUN apk add --no-cache dumb-init bash

FROM git-install as repo  
COPY . /application
WORKDIR /application
RUN pwd
RUN ls
RUN yarn
RUN mv .env.localhost .env
RUN yarn build:prod

